'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Moon, Sunrise, ArrowLeft, Loader2, Sparkles } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';
import { getSupabaseAuthHeaders } from '@/lib/supabase/authHeaders';
import ConciergeWaitlist from '@/components/home/ConciergeWaitlist';

/**
 * Concierge preview — shows Olivier "writing" a personalized Evening Brief /
 * Morning Wake-up / Wind-down for this trip's real Day 1, then an early-access
 * CTA. The brief text is generated by /api/trips/[tripId]/concierge-brief
 * (Claude, with a deterministic fallback), so the page is never empty.
 */

// Order + presentation of the three scheduled touches (CONCIERGE_PLAN §rhythm).
const BEATS = [
  { key: 'eveningBrief', icon: Moon, label: 'Evening brief', when: 'tonight · the night before' },
  { key: 'morningWakeup', icon: Sunrise, label: 'Morning wake-up', when: '~90 min before you go' },
  { key: 'windDown', icon: Moon, label: 'Wind-down', when: 'around 9pm' },
];

export default function ConciergeClient({ tripId, cityDisplay, dateRangeLabel, heroImage }) {
  const { session } = useAuth();
  const [briefs, setBriefs] = useState(null);
  const [status, setStatus] = useState('loading'); // 'loading' | 'ready' | 'error'

  useEffect(() => {
    let cancelled = false;
    setStatus('loading');

    (async () => {
      try {
        const res = await fetch(`/api/trips/${tripId}/concierge-brief`, {
          method: 'POST',
          headers: getSupabaseAuthHeaders(session, { 'Content-Type': 'application/json' }),
          body: JSON.stringify({}),
        });
        if (!res.ok) throw new Error(await res.text());
        const data = await res.json();
        if (cancelled) return;
        if (!data?.eveningBrief) throw new Error('Malformed brief');
        setBriefs(data);
        setStatus('ready');
      } catch (err) {
        console.error('[concierge] brief fetch failed', err);
        if (!cancelled) setStatus('error');
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [tripId, session]);

  return (
    <div className="min-h-screen bg-[#faf8f3]">
      {/* Hero */}
      <header className="relative overflow-hidden border-b border-amber-100/80">
        {heroImage && (
          <>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={heroImage} alt="" className="absolute inset-0 h-full w-full object-cover" />
            <div className="absolute inset-0 bg-gradient-to-t from-[#faf8f3] via-[#faf8f3]/85 to-[#faf8f3]/55" />
          </>
        )}
        <div className="relative mx-auto max-w-3xl px-6 pt-10 pb-12">
          <Link
            href={`/itineraries/${tripId}`}
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-gray-500 transition hover:text-gray-800"
          >
            <ArrowLeft className="h-4 w-4" /> Back to itinerary
          </Link>

          <div className="mt-6 flex items-center gap-2 text-blue-600 font-bold text-xs uppercase tracking-widest">
            <Sparkles className="h-3.5 w-3.5" /> Coming soon · Olivier, your concierge
          </div>
          <h1 className="font-display text-4xl md:text-5xl font-bold text-gray-900 mt-3 leading-[1.1]">
            A taste of your concierge.
          </h1>
          <p className="mt-4 text-lg text-gray-600 leading-relaxed">
            Here&apos;s how Olivier would open your trip to{' '}
            <span className="font-semibold text-gray-900">{cityDisplay}</span>
            {dateRangeLabel ? ` · ${dateRangeLabel}` : ''} — three quiet messages on your first day,
            in the voice of someone who lives there.
          </p>
        </div>
      </header>

      {/* Briefs */}
      <main className="mx-auto max-w-3xl px-6 py-12">
        {status === 'loading' && (
          <div className="flex flex-col items-center gap-3 rounded-2xl border border-amber-100/80 bg-white px-6 py-16 text-center shadow-sm">
            <Loader2 className="h-6 w-6 animate-spin text-blue-600" />
            <p className="font-semibold text-gray-900">Olivier is writing your brief…</p>
            <p className="text-sm text-gray-500">Reading your first day in {cityDisplay}.</p>
          </div>
        )}

        {status === 'error' && (
          <div className="rounded-2xl border border-amber-100/80 bg-white px-6 py-10 text-center shadow-sm">
            <p className="font-semibold text-gray-900">Olivier couldn&apos;t draft your brief just now.</p>
            <p className="mt-1 text-sm text-gray-500">Try again in a moment — the concierge is still in preview.</p>
          </div>
        )}

        {status === 'ready' && briefs && (
          <ul className="flex flex-col gap-5">
            {BEATS.map(({ key, icon: Icon, label, when }) => {
              const beat = briefs[key];
              if (!beat?.body) return null;
              return (
                <li
                  key={key}
                  className="rounded-2xl border border-amber-100/80 bg-white p-6 shadow-sm md:p-7"
                >
                  <div className="flex items-center gap-3">
                    <span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-50 text-blue-600">
                      <Icon className="h-5 w-5" />
                    </span>
                    <div className="min-w-0">
                      <p className="font-bold leading-tight text-gray-900">{label}</p>
                      <p className="text-xs uppercase tracking-wide text-gray-400">{when}</p>
                    </div>
                  </div>
                  <p className="mt-4 text-lg leading-relaxed text-gray-800">{beat.body}</p>
                  {beat.meta && (
                    <p className="mt-3 border-t border-gray-100 pt-3 text-sm font-medium text-gray-500">
                      {beat.meta}
                    </p>
                  )}
                </li>
              );
            })}
          </ul>
        )}

        {/* Early-access CTA */}
        <div className="mt-12">
          <p className="mb-4 text-center text-sm font-medium text-gray-500">
            This is a preview. Want Olivier on your real trips?
          </p>
          <div className="mx-auto max-w-md">
            <ConciergeWaitlist heading="Get early access" />
          </div>
        </div>
      </main>
    </div>
  );
}
