// Co-located static data for CityOverview's "Season by Season" section.
export const CITY_SEASONAL_NARRATIVES = {
  prague: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> are Prague at its finest. Spring brings blooming gardens in Petřín and Wallenstein Palace, Easter markets in Old Town Square, and the city shaking off winter's gray. Fall delivers golden light over the spires, harvest season, and the Signal Festival illuminating buildings with art projections. Temperatures hover 12–22°C—perfect for wandering cobblestoned streets. Aim for <strong>May or late September</strong> when crowds thin, prices ease, and the city belongs to you.`,
    summer: `<strong>July and August</strong> bring long days, outdoor beer gardens at full capacity, and every terrace along the Vltava humming with life. The trade-off: peak tourist season means Charles Bridge is impassable by 9am, Old Town Square is a selfie gauntlet, and hotel prices climb. Temperatures reach 25–30°C with occasional thunderstorms. If you visit, start early (castle at opening), retreat to parks and beer gardens in the afternoon heat, and embrace the late-night atmosphere when day-trippers leave.`,
    winter: `<strong>November through February</strong> reveals Prague's fairy-tale side. Snow dusts the Gothic spires, Christmas markets fill Old Town Square with mulled wine and trdelník, and you can actually see the Astronomical Clock without fighting crowds. Temperatures hover -2 to 5°C—cold but manageable with layers. Hotel prices drop 30-40%, and the city feels more local. This is the season for <strong>cozy pubs, candlelit cafés</strong>, and Prague Castle silhouetted against winter skies. December markets are magical; January-February are the quietest months.`,
    march: `Prague's awakening. Temperatures reach 8–14°C, café terraces tentatively reopen, and the first tourists arrive for Easter. This <strong>shoulder season offers excellent value</strong> with fewer crowds than what's coming. Gardens begin blooming mid-month, and the city transitions from winter coziness to spring energy. Pack layers—Czech springs are unpredictable—and enjoy the quiet before the summer rush.`
  },
  amsterdam: {
    springFall: `<strong>April through May</strong> and <strong>September through October</strong> are Amsterdam at its best. Spring brings tulip season—Keukenhof erupts in color through mid-May, and King's Day (April 27) transforms the city into an orange-clad street party. Fall delivers golden leaves along the canals, cozy café culture, and Amsterdam Dance Event in October. Temperatures hover 12–18°C, perfect for cycling. Aim for <strong>late April</strong> for tulips and King's Day, or <strong>late September</strong> for ideal museum weather and fewer tourists.`,
    summer: `<strong>June through August</strong> bring long days (sunset past 10pm), canal-side terraces packed until midnight, and festivals from Pride (early August) to open-air concerts in Vondelpark. The Dutch make the most of every sunny day. Trade-offs: peak tourist crowds, higher hotel prices, and the occasional rain shower that clears terraces in seconds. The city buzzes with energy, locals flee to the beaches on hot days, and getting a terrace seat requires patience. Book museums ahead and embrace the long evenings.`,
    winter: `<strong>November through February</strong> reveals Amsterdam's cozy side. Brown cafés glow with candlelight, ice skating comes to Museumplein, and the Amsterdam Light Festival (December-January) illuminates the canals with art installations. Temperatures hover 2–8°C—cold but rarely freezing. Hotel prices drop 30-40%, museum queues shrink, and you'll share the city with far fewer tourists. This is the season of <strong>gezelligheid</strong>—the untranslatable Dutch concept of cozy conviviality. Bring layers, embrace the early darkness, and spend long afternoons in cafés.`,
    march: `Amsterdam's awakening. Temperatures reach 8–12°C, the first brave souls reclaim the terraces, and the city shakes off winter gray. Tulip season begins mid-month, building toward the April peak. This <strong>shoulder season offers excellent value</strong> before King's Day crowds arrive. Expect some rain and pack layers—Dutch spring is fickle. But the daffodils are out, the museums are quiet, and locals emerge with genuine optimism about the approaching warmth.`
  },
  rome: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> are Rome at its finest. Temperatures hover between 18–25°C, outdoor dining fills every piazza, and golden light illuminates ancient ruins in ways that feel almost staged. Spring brings wisteria and Easter crowds; fall offers harvest season and film festivals. Aim for <strong>May or late September</strong>—perfect weather, manageable tourists, and the city humming with energy without summer's oppressive heat.`,
    summer: `<strong>July and August</strong> bring scorching heat (30–35°C), crushing humidity, and crowds that test your patience. But summer also means Romans fleeing to the coast, leaving the city to tourists and those who embrace the heat. Ferragosto (August 15) empties the city entirely—many restaurants close for weeks. If you visit, start early (Vatican at 8am), siesta hard (2–5pm indoors), and come alive after sunset when piazzas transform into open-air theaters.`,
    winter: `<strong>November through February</strong> reveals Rome's intimate side. Temperatures stay mild by European standards (5–12°C), queues shrink dramatically, and you can actually contemplate the Sistine Chapel without someone's elbow in your ribs. Hotel prices drop 30-40%. The trade-off? Shorter days, occasional rain, and some outdoor sites feel less magical. <strong>Christmas in Rome</strong> is special—Midnight Mass at St. Peter's, presepi (nativity scenes) everywhere, and festive markets. This is the <strong>best season for art and culture lovers</strong> who want space to breathe.`,
    march: `Rome's gentle awakening. Temperatures reach 15–18°C, outdoor terraces reopen, and the city shakes off winter. Easter brings papal ceremonies and significant crowds, so book ahead if visiting Holy Week. This <strong>shoulder season offers excellent value</strong> with spring flowers in the Borghese Gardens and fewer tourists than what's coming. Pack layers—Roman springs can be fickle—and embrace the occasional shower as part of the charm.`
  },
  barcelona: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> are Barcelona's sweet spots. Temperatures hover around 18–25°C, beaches are pleasant but not packed, and locals reclaim their city from summer's tourist crush. Outdoor terraces hum with vermut hour, Gaudí landmarks are actually enjoyable to visit, and golden evening light makes every Gothic Quarter corner photogenic. If it's your first visit, aim for <strong>May or late September</strong>—perfect weather, manageable crowds, and the city at its most livable.`,
    summer: `<strong>July and August</strong> bring scorching heat (30–35°C), sardine-packed beaches, and cruise ship crowds descending on La Rambla. This is peak season in every sense: highest prices, longest queues, and restaurants struggling to keep up. But summer also means beach parties, open-air festivals like Sónar and Grec, rooftop bars in full swing, and magical late nights when the city truly comes alive after 10pm. Book everything ahead—especially Sagrada Família—and embrace the Mediterranean chaos.`,
    winter: `<strong>November through February</strong> reveals a quieter Barcelona. Temperatures stay mild (8–15°C), rarely requiring more than a light jacket. Queues vanish at major attractions; you can actually take your time at the Picasso Museum. Hotel rates drop 30-40%. The tradeoff? Beach weather is gone, some outdoor activities close, and the city feels more local than tourist-friendly. <strong>December's Christmas markets</strong> and New Year's celebrations add festive sparkle. This is the <strong>best season for culture-focused travelers</strong> on a budget.`,
    march: `Barcelona's awakening. Temperatures climb to 15–18°C, almond trees bloom, and outdoor terraces cautiously reopen. The sea remains too cold for most, but this <strong>shoulder season offers excellent value</strong> before Easter crowds arrive. Pack layers—mornings can be crisp—and expect some spring showers. A perfect window for travelers who want Gaudí without the summer crush and tapas without tourist-inflated prices.`
  },
  paris: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> deliver the quintessential Paris experience. Temperatures settle into a comfortable 15–20°C, café terraces fill with conversation, and the city's gardens reach peak beauty—cherry blossoms in spring, golden leaves in autumn. Crowds exist but remain manageable. Light lingers late into evening. If you're planning your first visit, aim for <strong>May or September</strong>—they consistently offer the best balance of weather, crowds, and atmosphere.`,
    summer: `<strong>July and August</strong> bring the longest days—golden evenings stretching past 10pm, Bastille Day fireworks over the Eiffel Tower, Paris Plages pop-up beaches along the Seine, and open-air cinema under the stars. The trade-off? Peak crowds at every major attraction, the year's highest hotel rates, and many beloved neighborhood restaurants closing for the traditional August holiday. Book popular museums weeks ahead and expect to share the city with the world.`,
    winter: `<strong>November through February</strong> reveals Paris at its most intimate. Twinkling lights transform the Champs-Élysées, Christmas markets appear across the city, and you can linger over legendary hot chocolate at Angelina without the queues. Museum galleries feel nearly private. Temperatures hover between 3–8°C—cold but manageable with layers. Hotel rates drop significantly. If you don't mind bundling up, this is the <strong>best season for budget-conscious travelers</strong> and those who prefer a quieter, more local experience.`,
    march: `The city's gentle awakening. Temperatures climb toward 12°C, the first flowers appear in the Tuileries and Luxembourg Gardens, and outdoor terraces begin reopening. Pack layers and an umbrella—spring showers are part of the charm. This <strong>shoulder season offers excellent value</strong> before crowds arrive in earnest. A perfect time for travelers who want the romance of Paris without fighting for space.`
  },
  london: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> deliver London at its finest. Temperatures settle between 14–20°C, pub gardens fill with after-work pints, and the royal parks burst with daffodils then golden leaves. Chelsea Flower Show in May marks the social calendar; Open House London in September opens normally closed buildings for free. Light lingers past 9pm. If planning your first visit, aim for <strong>May or September</strong>—the sweet spot before summer crowds descend.`,
    summer: `<strong>July and August</strong> bring Wimbledon queues (bring strawberries), Proms at the Royal Albert Hall, and Notting Hill Carnival's Caribbean explosion. Daylight stretches past 10pm, rooftop bars thrive, and Hyde Park hosts outdoor cinema. The trade-off? Peak crowds at every attraction, accommodation at its most expensive, and the Tube becoming genuinely tropical (no air conditioning on older lines). Book museums ahead and embrace the glorious chaos.`,
    winter: `<strong>November through February</strong> reveals London at its most atmospheric. Christmas lights transform Oxford Street and Regent Street, ice rinks appear at Somerset House and the Tower, and cosy pubs become essential refuges serving warming ales and hearty pies. Temperatures hover 3–8°C—cold but manageable with layers. Hotel rates drop significantly. Theatre tickets are easier to find. If you don't mind bundling up, this is the <strong>best season for budget-conscious travelers</strong> who prefer a more local experience—and pantomime season is genuinely delightful.`,
    march: `London's tentative awakening. Temperatures climb toward 12°C, daffodils carpet the royal parks, and outdoor terraces cautiously reopen (Londoners treating 15°C as positively tropical). Pack layers—April showers are not merely a suggestion. This <strong>shoulder season offers excellent value</strong> before summer crowds arrive, and Londoners emerge blinking from hibernation with genuine optimism about the weather. It won't last, but enjoy it.`
  },
  lisbon: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> are Lisbon at its luminous best. Temperatures hover 18–25°C, miradouro sunsets paint the city gold, and outdoor dining fills every terrace. Spring brings the Santos Populares (June's sardine-grilling street parties); fall offers wine harvest festivals and golden light on tile-clad facades. This is peak season for a reason—but Lisbon absorbs crowds better than most capitals. Aim for <strong>May or late September</strong> for ideal weather and manageable tourism.`,
    summer: `<strong>July and August</strong> bring scorching heat (30–35°C) and Atlantic breezes that make it bearable. Lisboetas flee to the beaches—Cascais, Costa da Caparica—leaving the city to tourists who've timed their visits around heat. Festival season peaks with outdoor concerts, rooftop bars at full capacity, and late nights in Bairro Alto. The trade-off? Packed trams, sold-out Sintra palace tickets, and restaurants that can feel overwhelmed. Book ahead, start sightseeing early, and embrace the afternoon siesta. After sunset, the city comes alive.`,
    winter: `<strong>November through February</strong> reveals Lisbon's intimate side. Temperatures stay remarkably mild (10–16°C)—warmer than most European capitals—though rain is common. Fado sounds better in candlelit winter nights, queues vanish at Jerónimos Monastery, and hotel prices drop 30-40%. December brings festive markets and Christmas lights along Avenida da Liberdade. This is the <strong>best season for budget travelers</strong> and those who prefer fewer crowds. Pack layers and an umbrella, but expect pleasantly surprised by how mild Lisbon winters feel.`,
    march: `Lisbon's gentle awakening. Temperatures climb to 16–20°C, outdoor terraces reopen with enthusiasm, and the first warm days hint at summer. Jacaranda trees haven't bloomed yet (that's May), but gardens brighten and the light turns golden. This <strong>shoulder season offers excellent value</strong> before Easter crowds arrive. Pack layers—Atlantic weather is fickle—and enjoy Lisbon feeling genuinely local. Perfect for travelers who want the city's magic without fighting for miradouro space.`
  },
  vienna: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> deliver Vienna at its finest. Temperatures settle between 15–22°C, outdoor Schanigärten (café terraces) fill with conversation, and the Vienna Woods glow with spring blossoms or autumn gold. The opera and concert seasons are in full swing. Aim for <strong>May</strong> when gardens peak and Wiener Festwochen begins, or <strong>late September</strong> when harvest wines flow at Heurigen and cultural institutions launch their fall programs. These months offer the ideal balance of weather, cultural intensity, and manageable crowds.`,
    summer: `<strong>July and August</strong> bring warm days (25–30°C) and long evenings perfect for outdoor concerts, Danube swimming, and wine garden sessions. Many Viennese flee to the Alps or Croatian coast, lending the city a more relaxed pace. The State Opera closes mid-June through August, but open-air film screenings and summer festivals fill the gap. Trade-offs: no opera, some restaurants close for holidays, and occasional heat waves. But Schönbrunn's gardens are glorious, rooftop bars thrive, and the Donauinsel beach scene peaks.`,
    winter: `<strong>November through February</strong> reveals Vienna's romantic side. Christmas markets transform the city—Rathaus, Schönbrunn, Spittelberg—with mulled wine, handcrafted ornaments, and twinkling lights. The ball season peaks in January and February, culminating in the legendary Opera Ball. Temperatures hover between -1 and 5°C—cold but not brutal. Museum queues shrink, hotel prices drop 25-35%, and coffeehouses become essential refuges. The <strong>Vienna Philharmonic's New Year's Concert</strong> is the city's global calling card. This is the season for culture-seekers who embrace layering up.`,
    march: `Vienna's awakening. Temperatures climb toward 10–14°C, the first outdoor tables appear in sunny squares, and parks begin blooming. Easter brings special concerts and the arrival of spring markets. This <strong>shoulder season offers excellent value</strong> before summer prices arrive. Pack layers—Austrian springs are unpredictable—and enjoy Vienna feeling local before tour groups descend. Perfect for travelers who want opera season intensity without peak-season competition for tables and tickets.`
  },
  florence: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> represent Florence at its finest. Temperatures settle between 15–25°C, the Tuscan light achieves that golden quality artists have chased for centuries, and crowds—while present—remain manageable. Spring brings iris blooms at the Giardino dell'Iris and artichoke season in trattorias. Fall delivers grape harvest celebrations, truffle season, and that incomparable Tuscan afternoon light. <strong>Mid-May and late September</strong> offer the sweet spot: warm enough for gelato walks along the Arno, cool enough for museum hopping without overheating.`,
    summer: `<strong>July and August</strong> mean serious heat (32–38°C), serious crowds, and many Florentines fleeing to the coast. The Uffizi becomes a sauna of tour groups, and midday exploration requires strategic thinking. But trade-offs exist: long evenings perfect for aperitivo on Piazzale Michelangelo, Estate Fiorentina outdoor concerts, and restaurants eager for business. Budget travelers find deals as Italians vacation elsewhere. The key is <strong>morning museum strategy</strong>, long pranzo breaks, and embracing the passeggiata after sunset. The Oltrarno neighborhood stays cooler and more local.`,
    winter: `<strong>November through February</strong> reveals a different Florence—one where you might actually feel like a local rather than a tourist. Temperatures drop to 3–12°C, morning fog drifts along the Arno, and restaurants serve ribollita and bistecca without hour-long waits. Hotel prices drop 40-50%, major museums empty out, and you can actually contemplate the David without elbows in your ribs. Christmas brings lights along Via Tornabuoni and panforte in every bakery. The <strong>January sales</strong> make this leather-shopping paradise even more tempting. Pack layers and an umbrella—Tuscan winters are damp.`,
    march: `Florence's awakening. Temperatures climb toward 12–18°C, almond trees bloom across Tuscan hillsides, and Easter brings Scoppio del Carro—the exploding cart ceremony in Piazza del Duomo. This <strong>shoulder season offers excellent value</strong> before April crowds arrive. Museum lines exist but move. Outdoor markets fill with spring vegetables. Pack layers—March weather is unpredictable—but enjoy Florence feeling more like a living city than a museum. Perfect for travelers who want Renaissance immersion without Renaissance crowd levels.`
  },
  budapest: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> deliver Budapest at its absolute finest. Temperatures hover between 15–25°C, the thermal baths feel even more magical, and ruin bars spill onto courtyards without summer crush. Spring brings the Danube promenade alive with cherry blossoms and café terraces. Fall delivers wine harvest celebrations, paprika markets, and that golden light on Parliament that photographers chase. <strong>Late May and mid-September</strong> hit the sweet spot: warm enough for rooftop bars, cool enough for thermal soaking, and manageable crowds at Fisherman's Bastion.`,
    summer: `<strong>July and August</strong> bring heat (28–35°C), outdoor festivals, and crowds concentrated at thermal baths and ruin bars. Sziget Festival transforms Óbuda Island into Europe's biggest music party mid-August. The Danube becomes crucial—evening boat cruises, Margaret Island retreats, and riverside bars provide relief. Trade-offs: every tourist in Central Europe seems to visit simultaneously. But <strong>long summer evenings</strong> mean sunset drinks on the Buda hills, outdoor cinema screenings, and that particular Hungarian talent for making heat feel festive rather than oppressive.`,
    winter: `<strong>November through February</strong> reveals Budapest's romantic soul. Christmas markets fill Vörösmarty Square with mulled wine and chimney cakes. The thermal baths become essential—nothing matches steaming in 38°C Széchenyi water while snow falls around you. Hotel prices drop 30-40%, crowds thin dramatically, and ruin bars feel genuinely local again. Temperatures hover between -2 and 6°C—cold but the baths make it irrelevant. New Year's Eve along the Danube is legendary. The <strong>February wine festival</strong> in the Castle District draws connoisseurs without tourist crush.`,
    march: `Budapest's awakening. Temperatures climb toward 8–15°C, outdoor terraces begin opening, and the first tourists arrive for Easter. The Revolution Day celebrations on March 15th add cultural energy. This <strong>shoulder season offers excellent value</strong> before thermal bath queues build. The hills of Buda begin greening, and Jewish Quarter walking tours happen without crowds. Pack layers—Hungarian springs are unpredictable—but enjoy Budapest feeling like the locals' secret before summer shares it with the world.`
  },
  copenhagen: {
    springFall: `<strong>April through June</strong> and <strong>September through October</strong> represent Copenhagen at its finest. Spring arrives late but triumphantly—temperatures climb from 10°C to 20°C, Tivoli reopens with cherry blossoms, and café culture explodes along Nyhavn. Danes emerge from winter hibernation with an almost manic appreciation for sunshine. Fall brings <strong>hygge season</strong> beginnings, harvest menus in New Nordic restaurants, and that golden Scandinavian light photographers love. <strong>Late May and mid-September</strong> offer the sweet spot: long days, functioning outdoor life, and crowds that haven't peaked.`,
    summer: `<strong>June through August</strong> delivers Copenhagen's most magical weather. Temperatures reach 20–25°C, daylight extends past 10pm, and the entire city lives outdoors. Outdoor swimming harbors fill with Danes, Copenhagen Jazz Festival transforms the streets in July, and spontaneous gatherings appear wherever sun hits pavement. Trade-offs: peak tourist season means Nyhavn becomes a photo bottleneck and restaurant bookings require planning. But <strong>those endless summer evenings</strong>—cycling to a harbor bath, then wine along the canals until midnight—justify everything. This is when Copenhagen truly earns its reputation.`,
    winter: `<strong>November through February</strong> tests your commitment but rewards it with hygge immersion. Darkness descends by 4pm, temperatures hover between -2 and 5°C, and suddenly the Danish obsession with candles, blankets, and warm drinks makes complete sense. Tivoli transforms for Christmas with millions of lights. Hotel prices drop significantly, and you'll have museums mostly to yourself. The <strong>Christmas markets and New Year's Eve</strong> celebrations bring genuine Danish coziness. Pack your warmest layers and embrace the darkness—Copenhagen does its coziest work in winter.`,
    march: `Copenhagen's slow awakening. Temperatures hover between 3–8°C, but daylight lengthens noticeably and Danes begin venturing to sunny café terraces despite the chill. The city transitions from hygge hibernation to cautious optimism. This <strong>shoulder season offers excellent value</strong> before summer prices hit. Pack layers and accept that weather remains unpredictable—snow is possible, so is sunshine. Perfect for travelers who want Copenhagen's culture without Copenhagen's crowds, and who appreciate that first spring coffee outdoors even if it requires a blanket.`
  }
};

export const DEFAULT_SEASONAL_NARRATIVE = {
  springFall: `<strong>April through June</strong> and <strong>September through October</strong> typically offer the most pleasant weather for exploring. Temperatures are comfortable, crowds are manageable, and you'll enjoy longer days without peak-season prices.`,
  summer: `<strong>July and August</strong> bring the warmest weather and longest days, perfect for outdoor activities. Expect peak tourist crowds and higher prices. Book popular attractions in advance.`,
  winter: `<strong>November through February</strong> offers a quieter experience with lower prices. While weather can be challenging, you'll find shorter queues and a more authentic local atmosphere.`,
  march: `<strong>March</strong> marks the transition to spring. Weather can be unpredictable, but this shoulder season offers good value and fewer crowds.`
};
