import { Redis } from '@upstash/redis';
import { getRedisRestConfig } from '@/lib/redisEnv';
import { buildFortyEightHours } from '@/lib/city-guide/fortyEightHours';

export const runtime = 'nodejs';
// On-demand LLM generation (cities without a committed itinerary) can take ~45s;
// raise the function ceiling so it doesn't 504. Precomputed cities return instantly.
export const maxDuration = 60;

/**
 * GET /api/city-itinerary/48h?city=paris[&name=Paris]
 *
 * Returns a NYT "36 Hours"-style 48-hour itinerary for the city, generated by
 * Claude and grounded in the city's own data. Cached in two tiers so each city
 * costs at most one model call per window:
 *   L1 — in-memory (per serverless instance, instant)
 *   L2 — Upstash Redis (durable across instances / cold starts)
 * Falls back to L1-only when Redis isn't configured.
 *
 * Degrades to { itinerary: null } (200) when the city has no data, no API key,
 * or the model call fails — the UI shows a friendly empty state, never a crash.
 */

const CACHE_VERSION = 'v1';
const TTL_SECONDS = 30 * 24 * 60 * 60; // 30 days

const JSON_HEADERS = {
  'Cache-Control': 'public, max-age=86400, stale-while-revalidate=604800',
};

// L2: Redis (optional)
let redis = null;
const { url: redisUrl, token: redisToken } = getRedisRestConfig();
if (redisUrl && redisToken) {
  redis = new Redis({ url: redisUrl, token: redisToken });
}

// L1: in-memory, per-instance
const memoryCache = new Map();

const cacheKeyFor = (slug) => `city-48h:${CACHE_VERSION}:${slug}`;

async function readCache(key) {
  const mem = memoryCache.get(key);
  if (mem) return mem;
  if (!redis) return null;
  try {
    const cached = await redis.get(key);
    if (cached) {
      const data = typeof cached === 'string' ? JSON.parse(cached) : cached;
      memoryCache.set(key, data); // promote to L1
      return data;
    }
  } catch (err) {
    console.warn('[48h] Redis get failed:', err?.message || err);
  }
  return null;
}

async function writeCache(key, itinerary) {
  memoryCache.set(key, itinerary);
  if (!redis) return;
  try {
    await redis.setex(key, TTL_SECONDS, JSON.stringify(itinerary));
  } catch (err) {
    console.warn('[48h] Redis set failed:', err?.message || err);
  }
}

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const slug = (searchParams.get('city') || '').trim().toLowerCase();
  const displayName = searchParams.get('name')?.trim()
    || (slug ? slug.charAt(0).toUpperCase() + slug.slice(1) : '');

  if (!slug) {
    return Response.json({ itinerary: null, error: 'city is required' }, { status: 400 });
  }

  const key = cacheKeyFor(slug);
  const cached = await readCache(key);
  if (cached) {
    return Response.json({ itinerary: cached }, { headers: JSON_HEADERS });
  }

  const itinerary = await buildFortyEightHours(slug, displayName);

  // Cache successes only — a transient failure shouldn't poison the slot.
  if (itinerary) {
    await writeCache(key, itinerary);
  }

  return Response.json({ itinerary }, { headers: JSON_HEADERS });
}
